repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0 
    hooks:
    -   id: black
        exclude: notebooks/

-   repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --ClearMetadataPreprocessor.enabled=True --inplace

# repos:
# -   repo: local
#     hooks:
#     -   id: prospector
#         name: prospector
#         entry: prospector
#         language: python 
#         language_version: 3.10
#         additional_dependicies: 
#         additional_dependencies:
#             - ".[with_everything]"


        

#NOTE: running tests as a pre-commit hook has its problems:https://github.com/pre-commit/pre-commit/issues/761#issuecomment-394167542. Do this if its still absolutely required.
# -   repo: local
#     hooks:
#     -   id: tests
#         name: run tests
#         entry: pytest -v
#         language: system
#         types: [python]
#         always_run: true
#         pass_filenames: 
#TODO: implement prospector pre-cmmit hook