output-format: json

strictness: veryhigh
test-warnings: true
doc-warnings: true
max-line-length: 150
uses:
  - django
ignore-paths:
  - docs 
  - models 
  - references 
  - reports 
  - tests 
  - notebooks
ignore-patterns: 
    - __init__.py # ignore all init files in the entire repo 
    - migrations # ignore all directories called migrations in the entire repo 

# pycodestyle/pep8 coding guidelines   
pycodestyle:
    full: true

# pydocstyle/pep257 coding guidelines
pydocstyle:
    run: true
    disable: 
      - D213 # Igonore: Multi-line docstring summary should start at the second line
      - D400 # First line need not end with a period 
      - D415 # First line need not end with a period, question mark, or exclamation 
      - D203 # No blank line required before class docstring

# pylint
## enforces a coding standard, 
## looks for code smells, 
## and can make suggestions about how the code could be refactored
pylint:
    run: true
    disable:
      - wildcard-import # Star imports
      - too-few-public-methods
      - useless-object-inheritance
      - astroid-error #TODO: figure out what the problems actually are 
      - too-many-arguments
      - too-many-locals
      - no-value-for-parameter
      - django-not-configured
      - unused-argument
      - too-many-nested-blocks #TODO: simplify the data comparison method and remove this
      - cell-var-from-loop

# pyflakes
## analyzes programs and detects various errors
pyflakes:
    run: true

# mccabe
## measures code complexity 
mccabe:
    run: true

# dodgy
## looks for things which should not be in a public project like secret keys 
dodgy:
    run: true

# mypy 
## type checking 
mypy:
  run: true

# # bandit 
# ## looks for common security issues
# bandit:
#   run: true

# pyroma
## a tool to check your setup.py to ensure it is following best practices 
pyroma:
  run: true

# vulture
## finds unused classes, functions and variables in your code
vulture:
  run: true
  disable:
    - unused-variable
    - unused-function
    - unused-attribute
